export { default as ProTable, proTableProps } from './src/ProTable'
export type {
  ProTableApi,
  ProTableBatchAction,
  ProTableBatchActionsSlotProps,
  ProTableColumn,
  ProTableFormSlotProps,
  ProTableHeaderSlotProps,
  ProTableInst,
  ProTableOption,
  ProTablePageFields,
  ProTablePagination,
  ProTableProps,
  ProTableRecord,
  ProTableRequest,
  ProTableRequestResult,
  ProTableSearchComponent,
  ProTableSearchOption,
  ProTableSelectionSlotProps,
  ProTableSlots,
  ProTableSorter,
} from './src/types'
